<a href="https://colab.research.google.com/github/Rob85225/CSC-115/blob/main/Assignment_2_3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [11]:
import pandas as pd

# Load the dataset
df = pd.read_csv("https://raw.githubusercontent.com/Rob85225/CSC-115/main/nycflights.csv")

# Preview the data
df.head()

,year,month,day,dep_time,dep_delay,arr_time,arr_delay,carrier,tailnum,flight,origin,dest,air_time,distance,hour,minute
0,2013,6,30,940,15,1216,-4,VX,N626VA,407,JFK,LAX,313,2475,9,40
1,2013,5,7,1657,-3,2104,10,DL,N3760C,329,JFK,SJU,216,1598,16,57
2,2013,12,8,859,-1,1238,11,DL,N712TW,422,JFK,LAX,376,2475,8,59
3,2013,5,14,1841,-4,2122,-34,DL,N914DL,2391,JFK,TPA,135,1005,18,41
4,2013,7,21,1102,-3,1230,-8,9E,N823AY,3652,LGA,ORF,50,296,11,2

In [12]:
# American Airlines (AA) and Delta Airlines (DL)
aa_count = df[df['carrier'] == 'AA'].shape[0]
dl_count = df[df['carrier'] == 'DL'].shape[0]

print(f"American Airlines flights: {aa_count}")
print(f"Delta Airlines flights: {dl_count}")

American Airlines flights: 3188
Delta Airlines flights: 4751

In [13]:
# Filter for JFK origin
jfk_df = df[df['origin'] == 'JFK']

# Top destinations from JFK
top_dest_jfk = jfk_df['dest'].value_counts().head(5)

print("Top destinations from JFK:")
print(top_dest_jfk)

Top destinations from JFK:
dest
LAX    1115
SFO     832
BOS     585
MCO     529
SJU     471
Name: count, dtype: int64

In [14]:
# Group by origin and destination
origin_dest_counts = df.groupby(['origin', 'dest']).size().reset_index(name='flight_count')

print(origin_dest_counts.head())

  origin dest  flight_count
0    EWR  ALB            37
1    EWR  ANC             1
2    EWR  ATL           512
3    EWR  AUS            94
4    EWR  AVL            25

In [15]:
missing_dep_time = df['dep_time'].isna().sum()
print(f"Missing values in dep_time: {missing_dep_time}")

Missing values in dep_time: 0

In [16]:
# Group by carrier and calculate average departure delay
avg_dep_delay = df.groupby('carrier')['dep_delay'].mean().sort_values(ascending=False)

# Airline with highest average delay
highest_delay_airline = avg_dep_delay.idxmax()
highest_delay_value = avg_dep_delay.max()

print(f"Airline with highest average departure delay: {highest_delay_airline} ({highest_delay_value:.2f} minutes)")

Airline with highest average departure delay: HA (38.53 minutes)